FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY BeaTraction.sln ./
COPY BeaTraction.WebAPI/BeaTraction.WebAPI.csproj BeaTraction.WebAPI/
COPY BeaTraction.Application/BeaTraction.Application.csproj BeaTraction.Application/
COPY BeaTraction.Domain/BeaTraction.Domain.csproj BeaTraction.Domain/
COPY BeaTraction.Infrastructure/BeaTraction.Infrastructure.csproj BeaTraction.Infrastructure/

RUN dotnet restore

COPY . .

WORKDIR /src/BeaTraction.WebAPI

EXPOSE 5271

CMD ["dotnet", "run", "--urls", "http://0.0.0.0:5271"]
